apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.client.fullname }}
spec:
  selector:
    app: {{ .Values.client.name }}
  ports:
    - port: {{ .Values.client.service.port }}
      protocol: TCP
      targetPort: {{ .Values.client.service.port }}
  type: {{ .Values.client.service.type }}
