apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.client.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.client.name }}
  replicas: {{ .Values.client.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.client.name }}
    spec:
      containers:
        - name: student-app-client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.client.service.port }}
